import { fileURLToPath, pathToFileURL } from 'url'
import { platform } from 'process'
import path from 'path'

global.owner = [
    ['51907182818', 'お Onigiri-san ん⟅', true],
    ['549387368-7399']
]

global.mods = ['51907182818']
global.prems = ['51907182818', '549387368-7399']

global.prefix = '/'

global.rpg = {
    data: {
        exp: 0,
        coin: 10,
        nivel: 0,
        role: 'Novato'
    },
    cantidad: {
        mineria: 1500, //XP
        tiempoMinera: 2 * 60 * 60 * 1000, //2 horas
        robar: 1000, //XP
        tiempoRobar: 2 * 60 * 60 * 1000, //2 horas
        claimFree: 5000, //XP
        claimPrem: 20000, //XP
        TiempoClaim: 24 * 60 * 60 * 1000 //24 horas
    },
    precios: {
        coin: 100,
        nivel: 500
    },
    role: [
        { name: 'Novato', nivel: 1 },
        { name: 'Aprendiz', nivel: 2 },
        { name: 'Practicante', nivel: 3 },
        { name: 'Asistente', nivel: 4 },
        { name: 'Ayudante', nivel: 5 },
        { name: 'Oficial Junior', nivel: 6 },
        { name: 'Oficial', nivel: 7 },
        { name: 'Oficial Senior', nivel: 8 },
        { name: 'Supervisor', nivel: 9 },
        { name: 'Jefe de Equipo', nivel: 10 },
        { name: 'Coordinador', nivel: 11 },
        { name: 'Administrador', nivel: 12 },
        { name: 'Gerente Junior', nivel: 13 },
        { name: 'Gerente', nivel: 14 },
        { name: 'Gerente Senior', nivel: 15 },
        { name: 'Director Junior', nivel: 16 },
        { name: 'Director', nivel: 17 },
        { name: 'Director Senior', nivel: 18 },
        { name: 'Vicepresidente Junior', nivel: 19 },
        { name: 'Vicepresidente', nivel: 20 },
        { name: 'Vicepresidente Senior', nivel: 21 },
        { name: 'Presidente Junior', nivel: 22 },
        { name: 'Presidente', nivel: 23 },
        { name: 'Presidente Senior', nivel: 24 },
        { name: 'CEO Junior', nivel: 25 },
        { name: 'CEO', nivel: 26 },
        { name: 'CEO Senior', nivel: 27 },
        { name: 'Propietario', nivel: 28 },
        { name: 'Fundador', nivel: 29 },
        { name: 'Visionario', nivel: 30 },
        { name: 'Pionero', nivel: 31 },
        { name: 'Innovador', nivel: 32 },
        { name: 'Revolucionario', nivel: 33 },
        { name: 'Genio', nivel: 34 },
        { name: 'Maestro', nivel: 35 },
        { name: 'Experto', nivel: 36 },
        { name: 'Profesional', nivel: 37 },
        { name: 'Especialista', nivel: 38 },
        { name: 'Autoridad', nivel: 39 },
        { name: 'Líder', nivel: 40 },
        { name: 'Dominante', nivel: 41 },
        { name: 'Supremo', nivel: 42 },
        { name: 'Invencible', nivel: 43 },
        { name: 'Inigualable', nivel: 44 },
        { name: 'Insuperable', nivel: 45 },
        { name: 'Inconquistable', nivel: 46 },
        { name: 'Invulnerable', nivel: 47 },
        { name: 'Inmortal', nivel: 48 },
        { name: 'Divino', nivel: 49 },
        { name: 'Legendario', nivel: 50 },
        { name: 'Mítico', nivel: 51 },
        { name: 'Épico', nivel: 52 },
        { name: 'Heroico', nivel: 53 },
        { name: 'Majestuoso', nivel: 54 },
        { name: 'Regio', nivel: 55 },
        { name: 'Imperial', nivel: 56 },
        { name: 'Soberano', nivel: 57 },
        { name: 'Supremo', nivel: 58 },
        { name: 'Omnipotente', nivel: 59 },
        { name: 'Omnisciente', nivel: 60 },
        { name: 'Omnipresente', nivel: 61 },
        { name: 'Infinito', nivel: 62 },
        { name: 'Eterno', nivel: 63 },
        { name: 'Absoluto', nivel: 64 },
        { name: 'Universal', nivel: 65 },
        { name: 'Galáctico', nivel: 66 },
        { name: 'Cósmico', nivel: 67 },
        { name: 'Celestial', nivel: 68 },
        { name: 'Estelar', nivel: 69 },
        { name: 'Solar', nivel: 70 },
        { name: 'Lunar', nivel: 71 },
        { name: 'Planetario', nivel: 72 },
        { name: 'Astral', nivel: 73 },
        { name: 'Espacial', nivel: 74 },
        { name: 'Dimensional', nivel: 75 },
        { name: 'Temporal', nivel: 76 },
        { name: 'Cuántico', nivel: 77 },
        { name: 'Metafísico', nivel: 78 },
        { name: 'Espectral', nivel: 79 },
        { name: 'Fantasmal', nivel: 80 },
        { name: 'Etéreo', nivel: 81 },
        { name: 'Elemental', nivel: 82 },
        { name: 'Mágico', nivel: 83 },
        { name: 'Místico', nivel: 84 },
        { name: 'Espiritual', nivel: 85 },
        { name: 'Divino', nivel: 86 },
        { name: 'Sagrado', nivel: 87 },
        { name: 'Santo', nivel: 88 },
        { name: 'Angelical', nivel: 89 },
        { name: 'Arcángel', nivel: 90 },
        { name: 'Serafín', nivel: 91 },
        { name: 'Querubín', nivel: 92 },
        { name: 'Deidad', nivel: 93 },
        { name: 'Semidiós', nivel: 94 },
        { name: 'Dios', nivel: 95 },
        { name: 'Dios Mayor', nivel: 96 },
        { name: 'Dios Supremo', nivel: 97 },
        { name: 'Dios de Dioses', nivel: 98 },
        { name: 'Creador', nivel: 99 },
        { name: 'El Todo', nivel: 100 },
        { name: 'Supremo del Todo', nivel: 101 },
        { name: 'Rey del Supremo', nivel: 102 },
        { name: 'Soberano del Rey', nivel: 103 },
        { name: 'Monarca Supremo', nivel: 104 },
        { name: 'Emperador Divino', nivel: 105 },
        { name: 'Señor Celestial', nivel: 106 },
        { name: 'Maestro Infinito', nivel: 107 },
        { name: 'Conquistador Eterno', nivel: 108 },
        { name: 'Dueño Absoluto', nivel: 109 },
        { name: 'Rector Universal', nivel: 110 },
        { name: 'Gobernante Galáctico', nivel: 111 },
        { name: 'Caudillo Cósmico', nivel: 112 },
        { name: 'Rey Estelar', nivel: 113 },
        { name: 'Soberano Solar', nivel: 114 },
        { name: 'Monarca Lunar', nivel: 115 },
        { name: 'Emperador Planetario', nivel: 116 },
        { name: 'Regente Astral', nivel: 117 },
        { name: 'Dueño Espacial', nivel: 118 },
        { name: 'Maestro Dimensional', nivel: 119 },
        { name: 'Conquistador Temporal', nivel: 120 },
        { name: 'Dueño Cuántico', nivel: 121 },
        { name: 'Señor Metafísico', nivel: 122 },
        { name: 'Monarca Espectral', nivel: 123 },
        { name: 'Emperador Fantasmal', nivel: 124 },
        { name: 'Soberano Etéreo', nivel: 125 },
        { name: 'Monarca Elemental', nivel: 126 },
        { name: 'Emperador Mágico', nivel: 127 },
        { name: 'Señor Místico', nivel: 128 },
        { name: 'Maestro Espiritual', nivel: 129 },
        { name: 'Conquistador Divino', nivel: 130 },
        { name: 'Dueño Sagrado', nivel: 131 },
        { name: 'Regente Santo', nivel: 132 },
        { name: 'Rey Angelical', nivel: 133 },
        { name: 'Soberano Arcángel', nivel: 134 },
        { name: 'Monarca Serafín', nivel: 135 },
        { name: 'Emperador Querubín', nivel: 136 },
        { name: 'Señor Deidad', nivel: 137 },
        { name: 'Maestro Semidiós', nivel: 138 },
        { name: 'Conquistador Dios', nivel: 139 },
        { name: 'Dueño Dios Mayor', nivel: 140 },
        { name: 'Regente Dios Supremo', nivel: 141 },
        { name: 'Rey de Dioses', nivel: 142 },
        { name: 'Soberano Creador', nivel: 143 },
        { name: 'Monarca del Todo', nivel: 144 },
        { name: 'Emperador Supremo del Todo', nivel: 145 },
        { name: 'Señor del Rey Supremo', nivel: 146 },
        { name: 'Maestro Soberano del Todo', nivel: 147 },
        { name: 'Conquistador Monarca Supremo', nivel: 148 },
        { name: 'Dueño Emperador Divino', nivel: 149 },
        { name: 'Regente Señor Celestial', nivel: 150 },
        { name: 'Rey Maestro Infinito', nivel: 151 },
        { name: 'Soberano Conquistador Eterno', nivel: 152 },
        { name: 'Monarca Dueño Absoluto', nivel: 153 },
        { name: 'Emperador Rector Universal', nivel: 154 },
        { name: 'Señor Gobernante Galáctico', nivel: 155 },
        { name: 'Maestro Caudillo Cósmico', nivel: 156 },
        { name: 'Conquistador Rey Estelar', nivel: 157 },
        { name: 'Dueño Soberano Solar', nivel: 158 },
        { name: 'Regente Monarca Lunar', nivel: 159 },
        { name: 'Rey Emperador Planetario', nivel: 160 },
        { name: 'Soberano Regente Astral', nivel: 161 },
        { name: 'Monarca Dueño Espacial', nivel: 162 },
        { name: 'Emperador Maestro Dimensional', nivel: 163 },
        { name: 'Señor Conquistador Temporal', nivel: 164 },
        { name: 'Maestro Dueño Cuántico', nivel: 165 },
        { name: 'Conquistador Señor Metafísico', nivel: 166 },
        { name: 'Dueño Monarca Espectral', nivel: 167 },
        { name: 'Regente Emperador Fantasmal', nivel: 168 },
        { name: 'Rey Soberano Etéreo', nivel: 169 },
        { name: 'Monarca Monarca Elemental', nivel: 170 },
        { name: 'Emperador Emperador Mágico', nivel: 171 },
        { name: 'Señor Señor Místico', nivel: 172 },
        { name: 'Maestro Maestro Espiritual', nivel: 173 },
        { name: 'Conquistador Conquistador Divino', nivel: 174 },
        { name: 'Dueño Dueño Sagrado', nivel: 175 },
        { name: 'Regente Regente Santo', nivel: 176 },
        { name: 'Rey Rey Angelical', nivel: 177 },
        { name: 'Soberano Soberano Arcángel', nivel: 178 },
        { name: 'Monarca Monarca Serafín', nivel: 179 },
        { name: 'Emperador Emperador Querubín', nivel: 180 },
        { name: 'Señor Señor Deidad', nivel: 181 },
        { name: 'Maestro Maestro Semidiós', nivel: 182 },
        { name: 'Conquistador Conquistador Dios', nivel: 183 },
        { name: 'Dueño Dueño Dios Mayor', nivel: 184 },
        { name: 'Regente Regente Dios Supremo', nivel: 185 },
        { name: 'Rey Rey de Dioses', nivel: 186 }
    ]
}

global.__filename = function filename(pathURL = import.meta.url, rmPrefix = platform !== 'win32') { return rmPrefix ? /file:\/\/\//.test(pathURL) ? fileURLToPath(pathURL) : pathURL : pathToFileURL(pathURL).toString() }

global.__dirname = function dirname(pathURL) { return path.dirname(global.__filename(pathURL, true)) } 

